### ISSUE TITLE
Need a fix

### ISSUE THREAD

**Issue by philly306** [Disc0rdian/discord-boost-bot#1]
It keeps saying this and ive done all the steps including the Intents ive selected them all.

 bot = discord.Bot(intents=discord.Intents.all())
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by Disc0rdian** [comment]
> It keeps saying this and ive done all the steps including the Intents ive selected them all.
> 
> bot = discord.Bot(intents=discord.Intents.all()) AttributeError: module 'discord' has no attribute 'Bot'

Try doing
pip install py-cord

**Comment by philly306** [comment]
> > It keeps saying this and ive done all the steps including the Intents ive selected them all.
> > bot = discord.Bot(intents=discord.Intents.all()) AttributeError: module 'discord' has no attribute 'Bot'
> 
> Try doing pip install py-cord

already had that

**Comment by Disc0rdian** [comment]
> > > It keeps saying this and ive done all the steps including the Intents ive selected them all.
> > > bot = discord.Bot(intents=discord.Intents.all()) AttributeError: module 'discord' has no attribute 'Bot'
> > 
> > 
> > Try doing pip install py-cord
> 
> already had that

I just tested it. All the requirements in "requirements.txt" will 100% make it work. If it somehow still doesn't work for you then I am pretty sure its because you don't have python 3.9

**Comment by philly306** [comment]
> > > > It keeps saying this and ive done all the steps including the Intents ive selected them all.
> > > > bot = discord.Bot(intents=discord.Intents.all()) AttributeError: module 'discord' has no attribute 'Bot'
> > > 
> > > 
> > > Try doing pip install py-cord
> > 
> > 
> > already had that
> 
> I just tested it. All the requirements in "requirements.txt" will 100% make it work. If it somehow still doesn't work for you then I am pretty sure its because you don't have python 3.9

it could be because i do not have the correct python
